name: Groups

on: [push, workflow_dispatch]

jobs:
  id:
    name: id on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-ppc64le]

    steps:
      - name: change groups
        if: ${{ matrix.os }} == 'ubuntu-24.04-ppc64le'
        run: |
          id -u 
          id -g

          if [ "$(uname -m)" = "ppc64le" ]; then
            echo "original passwd"
            cat /etc/passwd
            sudo usermod -g "$(id -g)" runner
          fi
    
      - name: Run ID
        run: |
          id 
          id -u
          id -g

          cat /etc/passwd
