name: Groups

on: [push, workflow_dispatch]

jobs:
  id:
    name: id on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-ppc64le, ubuntu-24.04-ppc64le-p10, ubuntu-24.04-s390x]

    steps:
      - name: Run ID
        run: |
          id 
          id -u
          id -g

          cat /etc/passwd
